#3- Create a pod with the name nginx and with the image “nginx123” Use a pod-definition YAML file.
#4- What is the nginx pod status? ErrImagePull
#5- Change the nginx pod image to “nginx” check the status again

#kubectl apply -f nginx-pod.yaml
#kubectl delete -f nginx-pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
